// src/layouts/AppLayout/components/Footer/Footer.tsx
import { Flex, FlexItem, Text, TextContent, TextVariants } from '@patternfly/react-core';

export const Footer = (): JSX.Element => {
  return (
    <Flex alignItems={{ default: 'alignItemsCenter' }}>
      <Flex flex={{ default: 'flex_1' }}>
        <FlexItem>
          <TextContent>
            <Text component={TextVariants.p} className="pf-u-font-size-xs">
              <span className="pf-u-mr-md">
                Developer and Maintained by the{' '}
                <span className="pf-u-font-weight-bold">One Platform Team</span>
              </span>
              <span className="pf-u-mr-md">Internal use only</span>
              Find out more about similar associate run projects
            </Text>
          </TextContent>
        </FlexItem>
      </Flex>
      <FlexItem spacer={{ default: 'spacerLg' }}>
        <img src="/images/redhat.svg" alt="Red Hat" />
      </FlexItem>
    </Flex>
  );
};

// src/views/Footer.vue
<template>
  <footer>
    <div class="footer-text">
      <span>Developer and Maintained by the <b> One Platform Team </b></span>
      <span>Internal use only</span>
      <span>Find out more about similar associate run projects</span>
    </div>
    <div>
      <img src="@/assets/red-hat-logo.svg" alt="Redhat" />
    </div>
  </footer>
</template>

<style>
footer {
  height: 66px;
  background: #f4fbff;
  padding: 20px 10px;
  display: flex;
  align-items: center;
  font-size: 12px;
}

footer > .footer-text {
  display: inline-flex;
  flex-wrap: wrap;
  width: calc(100% + 12px);
}

footer > .footer-text > span {
  margin: 6px;
}
</style>
